### ISSUE TITLE
Calendar Section without Actual Days

### ISSUE THREAD

**Issue by garrettdavid1** [DrewDen/soloproject-tier1-ecalendar#6]
- Title and Current year in header
- Current month between previous and upcoming month
- Days of the week
- Arrows bordering the body of the calendar

**Utilize Flexbox to center everything vertically

**Comment by DrewDen** [comment]
David,
I believe I handled this issue.  I am going to push up my change in the calendar section branch.  Please feel free to pull that and take a look at my code to see what you think.  For the title, month, and weekdays I decide to keep them simple instead of putting a section or container name to them.
